version: '3.8'

services:
  organic_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organic_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - fuseki
      - ganache
    ports:
      - "8000:8000"
    environment:
      - FUSEKI_URL=http://fuseki:3030
      - GANACHE_URL=http://ganache:8545
    command: ["python3", "main.py"]

  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./ontology:/staging/ontology
      - ./data:/staging/data
      - ./rules:/staging/rules
      - ./queries:/staging/queries
      - fuseki_data:/fuseki
    environment:
      - ADMIN_PASSWORD=admin123
      - JVM_ARGS=-Xmx2g
    command: >
      bash -c "
        echo '🔄 Setting up Jena Fuseki with semantic reasoning...' &&
        
        # Create TDB2 database
        mkdir -p /fuseki/databases/organic_db &&
        
        # Load ontology and data
        echo '📥 Loading ontology...' &&
        tdb2.tdbloader --loc=/fuseki/databases/organic_db /staging/ontology/organic.owl &&
        
        echo '📥 Loading farm data...' &&
        tdb2.tdbloader --loc=/fuseki/databases/organic_db /staging/data/farm_data.ttl &&
        
        echo '🧠 Running SPARQL inference rules...' &&
        # Create inference queries for organic certification
        mkdir -p /staging/inference &&
        
        # Start Fuseki server
        echo '🚀 Starting Fuseki server...' &&
        /jena-fuseki/fuseki-server --loc=/fuseki/databases/organic_db --update /organic
      "

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: >
      --host 0.0.0.0
      --accounts 10
      --deterministic
      --mnemonic "test test test test test test test test test test test junk"
      --chainId 1337
      --gasLimit 10000000

volumes:
  fuseki_data: