version: '3.8'

services:
  organic_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organic_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - fuseki
      - ganache
    ports:
      - "8000:8000"
    environment:
      - FUSEKI_URL=http://fuseki:3030
      - GANACHE_URL=http://ganache:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - FUSEKI_USER=admin
      - FUSEKI_PASSWORD=admin123
    command: ["python3", "main.py"]
    networks:
      - semantic_net

  fuseki:
    image: stain/jena-fuseki:5.1.0
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jena:/jena                    # ✅ fix path
      - ./ontology:/staging/ontology
      - ./data:/staging/data
      - ./rules:/staging/rules
      - ./queries:/staging/queries
      - fuseki_data:/fuseki
      - ./jena/organic_rules.rules:/staging/jena/organic_rules.rules:ro
    environment:
      - ADMIN_PASSWORD=admin123
      - JVM_ARGS=-Xmx2g
    command: ["sh", "-c", "/jena/run_jena.sh"]
    networks:
      - semantic_net

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: >
      --host 0.0.0.0
      --accounts 10
      --deterministic
      --mnemonic "test test test test test test test test test test test junk"
      --chainId 1337
      --gasLimit 10000000
    networks:
      - semantic_net

  ui:
    build: ./ui
    container_name: ui
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
      - ./proofs:/app/proofs
    depends_on:
      - organic_app
      - fuseki                         # ✅ optional: UI might query it directly
    environment:
      - FUSEKI_URL=http://fuseki:3030  # ✅ make sure UI frontend/backend knows this
    networks:
      - semantic_net

volumes:
  fuseki_data:

networks:
  semantic_net:
    driver: bridge
